### ISSUE TITLE
[1.12.2] Incompatible with Controlling and Universal Tweaks.

### ISSUE THREAD

**Issue by sunshinekitsune** [Mr-Zombii/KeybindCFG#5]
KeybindCFG seems to be incapable of locking keybinds with [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling). No error is generated, just nothing happens. I presume it has to do with conflicting GUI changes.

Additionally, KeybindCFG is incompatible with [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks). There is actually a mixin error for this, no clue as to what exactly causes it in Universal Tweaks. 
```
[09:11:48] [Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.tweaks.misc.gui.keybindlistentry.json:UTKeyEntryMixin from mod unknown-owner -> net.minecraft.client.gui.GuiKeyBindingList$KeyEntry: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/client/gui/GuiKeyBindingList$KeyEntry::utIndentEntryText with priority 1000 cannot inject into net/minecraft/client/gui/GuiKeyBindingList$KeyEntry::func_192634_a(IIIIIIIZF)V merged by me.zombii.keybindcfg.mixin.KeyEntryMixin with priority 1000 [redirect$zgc000$unknown_owner$utIndentEntryText(Lnet/minecraft/client/gui/FontRenderer;Ljava/lang/String;III)I -> Prepare ->  -> { target: func_192634_a(IIIIIIIZF)V }]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/client/gui/GuiKeyBindingList$KeyEntry::utIndentEntryText with priority 1000 cannot inject into net/minecraft/client/gui/GuiKeyBindingList$KeyEntry::func_192634_a(IIIIIIIZF)V merged by me.zombii.keybindcfg.mixin.KeyEntryMixin with priority 1000 [redirect$zgc000$unknown_owner$utIndentEntryText(Lnet/minecraft/client/gui/FontRenderer;Ljava/lang/String;III)I -> Prepare ->  -> { target: func_192634_a(IIIIIIIZF)V }]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:365) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:236) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:204) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:55) ~[sponge-mixin-0.20.7+mixin.0.8.7.jar:0.20.7+mixin.0.8.7]
	at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.14.0.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:332) [foundation-0.14.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) [foundation-0.14.0.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:244) [foundation-0.14.0.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:267) [foundation-0.14.0.jar:?]
	at net.minecraft.client.gui.GuiKeyBindingList.<init>(GuiKeyBindingList.java:49) [bmd.class:?]
	at us.getfluxed.controlsearch.client.gui.GuiNewKeyBindingList.<init>(GuiNewKeyBindingList.java:31) [GuiNewKeyBindingList.class:?]
	at us.getfluxed.controlsearch.client.gui.GuiNewControls.func_73866_w_(GuiNewControls.java:62) [GuiNewControls.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) [blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:996) [bib.class:?]
	at net.minecraft.client.gui.GuiOptions.func_146284_a(SourceFile:152) [ble.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1741) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119) [LaunchHandler.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.14.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by Mr-Zombii** [comment]
Oh boy, lets see what I can do.

**Comment by Mr-Zombii** [comment]
This may take a few days since I am having massive trouble getting it to launch since forge is acting up & my gradle thingamabob is kinda broken.

**Comment by NuruddinPlays** [comment]
A few months late but can also confirm the Controlling issue with the 1.20.1 version of KeybindCFG

**Comment by Mr-Zombii** [comment]
i gotta sort out my time management...

**Comment by Mr-Zombii** [comment]
and this

**Comment by Mr-Zombii** [comment]
I went back the code and something that is used to build the mod is broken :(, idk if i can fix it.
